name = "arb-allday4"
main = "index.js"
compatibility_date = "2025-01-27"

[assets]
directory = "./public"
binding   = "ASSETS"

[[kv_namespaces]]
binding = "ARB_HOME_PAGES"
id = "5e308ed820e44f4e88669f135afffe4a"